name: Swiss Route API

services:
  postgres-datasource:
    image: postgres:18.3
    environment:
      POSTGRES_USER: ${SWISS_ROUTE_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SWISS_ROUTE_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SWISS_ROUTE_DATASOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - swissroute-postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SWISS_ROUTE_DATASOURCE_USERNAME} -d ${SWISS_ROUTE_DATASOURCE_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always
    networks:
      - swissroute-api-network

  swissroute-api:
    #image: ghcr.io/sebas679og/swiss-route:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres-datasource:
        condition: service_healthy
    environment:
      SWISS_ROUTE_LEVEL_LOGIN: ${SWISS_ROUTE_LEVEL_LOGIN}
      SWISS_ROUTE_DATASOURCE_USERNAME: ${SWISS_ROUTE_DATASOURCE_USERNAME}
      SWISS_ROUTE_DATASOURCE_PASSWORD: ${SWISS_ROUTE_DATASOURCE_PASSWORD}
      SWISS_ROUTE_DATASOURCE_URL: jdbc:postgresql://postgres-datasource:5432/${SWISS_ROUTE_DATASOURCE_DB}
      SWISS_ROUTE_JPA_DDL: ${SWISS_ROUTE_JPA_DDL}
      SWISS_ROUTE_JPA_SHOW_SQL: ${SWISS_ROUTE_JPA_SHOW_SQL}
      SWISS_ROUTE_TRANSPORT_API_BASE_URL: ${SWISS_ROUTE_TRANSPORT_API_BASE_URL}
      SWISS_ROUTE_TRANSPORT_API_CONNECT_TIMEOUT_MS: ${SWISS_ROUTE_TRANSPORT_API_CONNECT_TIMEOUT_MS}
      SWISS_ROUTE_TRANSPORT_API_READ_TIMEOUT_MS: ${SWISS_ROUTE_TRANSPORT_API_READ_TIMEOUT_MS}
      SWISS_ROUTE_TRANSPORT_API_WRITE_TIMEOUT_MS: ${SWISS_ROUTE_TRANSPORT_API_WRITE_TIMEOUT_MS}
      SWISS_ROUTE_TRANSPORT_API_MEMORY_SIZE_MB: ${SWISS_ROUTE_TRANSPORT_API_MEMORY_SIZE_MB}
      SWISS_ROUTE_ALLOWED_METHODS: ${SWISS_ROUTE_ALLOWED_METHODS}
      SWISS_ROUTE_ALLOWED_ORIGINS: ${SWISS_ROUTE_ALLOWED_ORIGINS}
      SWISS_ROUTE_MAX_AGE: ${SWISS_ROUTE_MAX_AGE}
      SWISS_ROUTE_JWT_SECRET: ${SWISS_ROUTE_JWT_SECRET}
      SWISS_ROUTE_JWT_EXPIRATION: ${SWISS_ROUTE_JWT_EXPIRATION}
      SWISS_ROUTE_TOKEN_TYPE: ${SWISS_ROUTE_TOKEN_TYPE}
      SWAGGER_UI_DOCUMENTATION_ENABLED: ${SWAGGER_UI_DOCUMENTATION_ENABLED}
    restart: on-failure
    networks:
      - swissroute-api-network

networks:
  swissroute-api-network:
    driver: bridge

volumes:
  swissroute-postgres-data: